export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const Fetch_Products = "Fetch_Products";
export const FILTER_PRODUCTS_BY_PRICE = "FILTER_PRODUCTS_BY_PRICE";
export const SELECT_ONE_PRODUCT = "SELECT_ONE_PRODUCT";
export const REMOVE_ONE_PRODUCT = "REMOVE_ONE_PRODUCT";
export const SELECT_ALL_PRODUCT = "SELECT_ALL_PRODUCT";
export const REMOVE_ALL_PRODUCT = "REMOVE_ALL_PRODUCT";
